import setuptools

with open('VERSION.txt', 'r') as f:
    version = f.read().strip()

setuptools.setup(
    name="odoo14-addons-akretion-odoo-usability",
    description="Meta package for akretion-odoo-usability Odoo addons",
    version=version,
    install_requires=[
        'odoo14-addon-account_bank_reconciliation_summary_xlsx',
        'odoo14-addon-account_default_report_without_paiement',
        'odoo14-addon-account_invoice_margin',
        'odoo14-addon-account_invoice_update_wizard',
        'odoo14-addon-account_invoice_update_wizard_payment_mode',
        'odoo14-addon-account_menu_usability',
        'odoo14-addon-account_move_label_copy',
        'odoo14-addon-account_payment_line_manual_account',
        'odoo14-addon-account_usability',
        'odoo14-addon-base_company_extension',
        'odoo14-addon-base_dynamic_list',
        'odoo14-addon-base_mail_sender_bcc',
        'odoo14-addon-base_partner_one2many_phone',
        'odoo14-addon-base_partner_ref',
        'odoo14-addon-base_usability',
        'odoo14-addon-commission_simple',
        'odoo14-addon-commission_simple_agent',
        'odoo14-addon-crm_usability',
        'odoo14-addon-delivery_usability',
        'odoo14-addon-developer_menu',
        'odoo14-addon-eradicate_quick_create',
        'odoo14-addon-hr_contract_usability',
        'odoo14-addon-intrastat_product_type',
        'odoo14-addon-link_tracker_usability',
        'odoo14-addon-mail_no_portal',
        'odoo14-addon-mail_usability',
        'odoo14-addon-mass_mailing_usability',
        'odoo14-addon-mrp_average_cost',
        'odoo14-addon-mrp_no_product_template_menu',
        'odoo14-addon-mrp_subcontracting_usability',
        'odoo14-addon-mrp_usability',
        'odoo14-addon-partner_products_shortcut',
        'odoo14-addon-partner_tree_default_account',
        'odoo14-addon-partner_tree_default_base',
        'odoo14-addon-partner_tree_default_contacts',
        'odoo14-addon-pos_config_single_user',
        'odoo14-addon-pos_product_tree_default',
        'odoo14-addon-pos_usability',
        'odoo14-addon-product_category_tax',
        'odoo14-addon-product_detailed_type',
        'odoo14-addon-product_detailed_type_stock',
        'odoo14-addon-product_manager_group',
        'odoo14-addon-product_manager_group_stock',
        'odoo14-addon-product_no_translation',
        'odoo14-addon-product_print_zpl_barcode',
        'odoo14-addon-product_priority_star',
        'odoo14-addon-product_usability',
        'odoo14-addon-project_usability',
        'odoo14-addon-purchase_product_tree_default',
        'odoo14-addon-purchase_stock_usability',
        'odoo14-addon-purchase_usability',
        'odoo14-addon-sale_agent',
        'odoo14-addon-sale_confirm_wizard',
        'odoo14-addon-sale_crm_usability',
        'odoo14-addon-sale_down_payment',
        'odoo14-addon-sale_margin_no_onchange',
        'odoo14-addon-sale_no_optional_product',
        'odoo14-addon-sale_no_preview_button',
        'odoo14-addon-sale_order_add_bom',
        'odoo14-addon-sale_order_route',
        'odoo14-addon-sale_product_tree_default',
        'odoo14-addon-sale_purchase_no_product_template_menu',
        'odoo14-addon-sale_quotation_title',
        'odoo14-addon-sale_show_transaction',
        'odoo14-addon-sale_stock_usability',
        'odoo14-addon-sale_usability',
        'odoo14-addon-sales_team_usability',
        'odoo14-addon-shopinvader_usability',
        'odoo14-addon-stock_account_usability',
        'odoo14-addon-stock_inventory_usability',
        'odoo14-addon-stock_move_line_auto_fill_all',
        'odoo14-addon-stock_no_product_template_menu',
        'odoo14-addon-stock_picking_batch_usability',
        'odoo14-addon-stock_picking_type_default_partner',
        'odoo14-addon-stock_product_tree_default',
        'odoo14-addon-stock_quant_package_move_wizard',
        'odoo14-addon-stock_reception_usability',
        'odoo14-addon-stock_usability',
        'odoo14-addon-stock_valuation_xlsx',
        'odoo14-addon-stock_valuation_xlsx_viewer',
        'odoo14-addon-web_tab_title',
    ],
    classifiers=[
        'Programming Language :: Python',
        'Framework :: Odoo',
        'Framework :: Odoo :: 14.0',
    ]
)
